// Generated by Rivet. Do not edit by hand.
#pragma once

#include <cstdint>
#include <exception>
#include <functional>
#include <future>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <variant>
#include <vector>

#include "backend.hpp"

namespace rivet_app {
inline constexpr char kModuleName[] = "backend";
inline constexpr char kEntryName[] = "start";

template <typename T>
struct Result {
  std::optional<T> value;
  std::exception_ptr error;
  bool succeeded() const noexcept { return value.has_value() && !error; }
  T const& get() const { if (error) std::rethrow_exception(error); if (!value) throw std::runtime_error("Rivet async result has no value"); return *value; }
};

template <>
struct Result<void> {
  std::exception_ptr error;
  bool succeeded() const noexcept { return !error; }
  void get() const { if (error) std::rethrow_exception(error); }
};

namespace detail {
inline rivet::Value encode_String(std::string const& v) { return rivet::Value(v); }
inline rivet::Value encode_Bytes(rivet::Bytes const& v) { return rivet::Value(v); }
inline rivet::Value encode__List_String_(std::vector<std::string> const& xs) { rivet::Value::List r; r.reserve(xs.size()); for (auto const& x : xs) r.push_back(encode_String(x)); return rivet::Value(std::move(r)); }
inline rivet::Value encode__List_List_String_(std::vector<std::vector<std::string>> const& xs) { rivet::Value::List r; r.reserve(xs.size()); for (auto const& x : xs) r.push_back(encode__List_String_(x)); return rivet::Value(std::move(r)); }

inline std::string decode_String(rivet::Value const& v) { if (auto p = std::get_if<std::string>(&v.data)) return *p; throw std::runtime_error("Rivet result type mismatch: String"); }
inline rivet::Bytes decode_Bytes(rivet::Value const& v) { if (auto p = std::get_if<rivet::Bytes>(&v.data)) return *p; throw std::runtime_error("Rivet result type mismatch: Bytes"); }
inline std::vector<std::string> decode__List_String_(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p) throw std::runtime_error("Rivet result type mismatch: (List String)"); std::vector<std::string> r; r.reserve(p->size()); for (auto const& x : *p) r.push_back(decode_String(x)); return r; }
inline std::vector<std::vector<std::string>> decode__List_List_String_(rivet::Value const& v) { auto p = std::get_if<rivet::Value::List>(&v.data); if (!p) throw std::runtime_error("Rivet result type mismatch: (List (List String))"); std::vector<std::vector<std::string>> r; r.reserve(p->size()); for (auto const& x : *p) r.push_back(decode__List_String_(x)); return r; }
}  // namespace detail

class API {
 public:
  explicit API(rivet::windows::Backend& backend) : backend_(backend) {}

  std::future<std::string> diagram_diag(std::string pattern) { auto raw = backend_.call("diagram-diag", rivet::Value::List{detail::encode_String(pattern)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::string { return detail::decode_String(raw.get()); }); }
  [[nodiscard]] std::uint64_t diagram_diag_async(std::string pattern, std::function<void(Result<std::string>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("diagram-diag", rivet::Value::List{detail::encode_String(pattern)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<std::string> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_String(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<rivet::Bytes> diagram_png(std::string pattern) { auto raw = backend_.call("diagram-png", rivet::Value::List{detail::encode_String(pattern)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> rivet::Bytes { return detail::decode_Bytes(raw.get()); }); }
  [[nodiscard]] std::uint64_t diagram_png_async(std::string pattern, std::function<void(Result<rivet::Bytes>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("diagram-png", rivet::Value::List{detail::encode_String(pattern)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<rivet::Bytes> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Bytes(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::string> explain_text(std::string pattern) { auto raw = backend_.call("explain-text", rivet::Value::List{detail::encode_String(pattern)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::string { return detail::decode_String(raw.get()); }); }
  [[nodiscard]] std::uint64_t explain_text_async(std::string pattern, std::function<void(Result<std::string>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("explain-text", rivet::Value::List{detail::encode_String(pattern)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<std::string> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_String(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::vector<std::vector<std::string>>> lint_rows(std::string pattern) { auto raw = backend_.call("lint-rows", rivet::Value::List{detail::encode_String(pattern)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::vector<std::vector<std::string>> { return detail::decode__List_List_String_(raw.get()); }); }
  [[nodiscard]] std::uint64_t lint_rows_async(std::string pattern, std::function<void(Result<std::vector<std::vector<std::string>>>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("lint-rows", rivet::Value::List{detail::encode_String(pattern)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<std::vector<std::vector<std::string>>> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode__List_List_String_(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::vector<std::vector<std::string>>> match_rows(std::string pattern, std::string text) { auto raw = backend_.call("match-rows", rivet::Value::List{detail::encode_String(pattern), detail::encode_String(text)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::vector<std::vector<std::string>> { return detail::decode__List_List_String_(raw.get()); }); }
  [[nodiscard]] std::uint64_t match_rows_async(std::string pattern, std::string text, std::function<void(Result<std::vector<std::vector<std::string>>>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("match-rows", rivet::Value::List{detail::encode_String(pattern), detail::encode_String(text)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<std::vector<std::vector<std::string>>> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode__List_List_String_(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::string> report_html(std::string pattern, std::string text) { auto raw = backend_.call("report-html", rivet::Value::List{detail::encode_String(pattern), detail::encode_String(text)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::string { return detail::decode_String(raw.get()); }); }
  [[nodiscard]] std::uint64_t report_html_async(std::string pattern, std::string text, std::function<void(Result<std::string>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("report-html", rivet::Value::List{detail::encode_String(pattern), detail::encode_String(text)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<std::string> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_String(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::string> status(std::string pattern) { auto raw = backend_.call("status", rivet::Value::List{detail::encode_String(pattern)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::string { return detail::decode_String(raw.get()); }); }
  [[nodiscard]] std::uint64_t status_async(std::string pattern, std::function<void(Result<std::string>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("status", rivet::Value::List{detail::encode_String(pattern)}, [completion = std::move(completion)](rivet::windows::CallResult raw) mutable { Result<std::string> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_String(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }

 private:
  rivet::windows::Backend& backend_;
};

}  // namespace rivet_app
