// Generated by Rivet. Do not edit by hand.
import Foundation
import RivetRuntime

public enum RivetGeneratedError: Error { case typeMismatch(String); case unknownEvent(String) }
public enum RivetGeneratedConfig {
    public static let moduleName = "backend"
    public static let entryName = "start"
    public static let displayName = "RegexMate"
    public static let version = "0.4.0"
    public static let build: Int64 = 2
    public static let identifier = "site.jrtx.regexmate"
    public static let releaseChannel = "stable"
}

private func encode_String(_ v: String) -> RivetValue { .string(v) }
private func encode_Bytes(_ v: Data) -> RivetValue { .bytes(v) }
private func encode__List_String_(_ v: [String]) -> RivetValue { .list(v.map(encode_String)) }
private func encode__List_List_String_(_ v: [[String]]) -> RivetValue { .list(v.map(encode__List_String_)) }

private func decode_String(_ v: RivetValue) throws -> String { guard case .string(let x) = v else { throw RivetGeneratedError.typeMismatch("String") }; return x }
private func decode_Bytes(_ v: RivetValue) throws -> Data { guard case .bytes(let x) = v else { throw RivetGeneratedError.typeMismatch("Bytes") }; return x }
private func decode__List_String_(_ v: RivetValue) throws -> [String] { guard case .list(let xs) = v else { throw RivetGeneratedError.typeMismatch("(List String)") }; return try xs.map(decode_String) }
private func decode__List_List_String_(_ v: RivetValue) throws -> [[String]] { guard case .list(let xs) = v else { throw RivetGeneratedError.typeMismatch("(List (List String))") }; return try xs.map(decode__List_String_) }

public struct RivetAPI: Sendable {
    public let client: RivetClient
    public init(client: RivetClient) { self.client = client }

    public func diagram_diag(pattern: String) async throws -> String {
        let result = try await client.call("diagram-diag", arguments: [encode_String(pattern)])
        return try decode_String(result)
    }
    public func diagram_png(pattern: String) async throws -> Data {
        let result = try await client.call("diagram-png", arguments: [encode_String(pattern)])
        return try decode_Bytes(result)
    }
    public func explain_text(pattern: String) async throws -> String {
        let result = try await client.call("explain-text", arguments: [encode_String(pattern)])
        return try decode_String(result)
    }
    public func lint_rows(pattern: String) async throws -> [[String]] {
        let result = try await client.call("lint-rows", arguments: [encode_String(pattern)])
        return try decode__List_List_String_(result)
    }
    public func match_rows(pattern: String, text: String) async throws -> [[String]] {
        let result = try await client.call("match-rows", arguments: [encode_String(pattern), encode_String(text)])
        return try decode__List_List_String_(result)
    }
    public func report_html(pattern: String, text: String) async throws -> String {
        let result = try await client.call("report-html", arguments: [encode_String(pattern), encode_String(text)])
        return try decode_String(result)
    }
    public func status(pattern: String) async throws -> String {
        let result = try await client.call("status", arguments: [encode_String(pattern)])
        return try decode_String(result)
    }
}
