// Generated by Rivet. Do not edit by hand.
#pragma once

#include <cstdint>
#include <exception>
#include <functional>
#include <future>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <variant>
#include <vector>

#include "backend.hpp"

namespace rivet_app {
inline constexpr char kModuleName[] = "backend";
inline constexpr char kEntryName[] = "start";

template <typename T>
struct Result {
  std::optional<T> value;
  std::exception_ptr error;
  bool succeeded() const noexcept { return value.has_value() && !error; }
  T const& get() const { if (error) std::rethrow_exception(error); if (!value) throw std::runtime_error("Rivet async result has no value"); return *value; }
};

template <>
struct Result<void> {
  std::exception_ptr error;
  bool succeeded() const noexcept { return !error; }
  void get() const { if (error) std::rethrow_exception(error); }
};

namespace detail {
inline rivet::Value encode_String(std::string const& v) { return rivet::Value(v); }
inline rivet::Value encode_Void() { return rivet::Value{}; }
inline rivet::Value encode_Int64(std::int64_t v) { return rivet::Value(v); }

inline std::string decode_String(rivet::Value const& v) { if (auto p = std::get_if<std::string>(&v.data)) return *p; throw std::runtime_error("Rivet result type mismatch: String"); }
inline void decode_Void(rivet::Value const& v) { if (!std::holds_alternative<std::monostate>(v.data)) throw std::runtime_error("Rivet result type mismatch: Void"); }
inline std::int64_t decode_Int64(rivet::Value const& v) { if (auto p = std::get_if<std::int64_t>(&v.data)) return *p; throw std::runtime_error("Rivet result type mismatch: Int64"); }
}  // namespace detail

struct NotificationEvent { std::string value; };
using Event = std::variant<NotificationEvent>;
inline Event decode_event(std::string const& name, rivet::Value const& value) {
  if (name == "notification") return Event{NotificationEvent{detail::decode_String(value)}};
  throw std::runtime_error("unknown Rivet event: " + name);
}

class API {
 public:
  explicit API(rivet::linux_runtime::Backend& backend) : backend_(backend) {}

  std::future<std::string> greet(std::string name) { auto raw = backend_.call("greet", rivet::Value::List{detail::encode_String(name)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::string { return detail::decode_String(raw.get()); }); }
  [[nodiscard]] std::uint64_t greet_async(std::string name, std::function<void(Result<std::string>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("greet", rivet::Value::List{detail::encode_String(name)}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<std::string> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_String(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<void> notify(std::string message) { auto raw = backend_.call("notify", rivet::Value::List{detail::encode_String(message)}); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> void { detail::decode_Void(raw.get()); }); }
  [[nodiscard]] std::uint64_t notify_async(std::string message, std::function<void(Result<void>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.request_async("notify", rivet::Value::List{detail::encode_String(message)}, [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<void> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); detail::decode_Void(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }

  // Shared state
  std::future<std::int64_t> get_counter() { auto raw = backend_.get_state("counter"); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::int64_t { return detail::decode_Int64(raw.get()); }); }
  [[nodiscard]] std::uint64_t get_counter_async(std::function<void(Result<std::int64_t>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.get_state_async("counter", [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<std::int64_t> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Int64(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }
  std::future<std::int64_t> set_counter(std::int64_t value) { auto raw = backend_.set_state("counter", detail::encode_Int64(value)); return std::async(std::launch::deferred, [raw = std::move(raw)]() mutable -> std::int64_t { return detail::decode_Int64(raw.get()); }); }
  [[nodiscard]] std::uint64_t set_counter_async(std::int64_t value, std::function<void(Result<std::int64_t>)> completion) { if (!completion) throw std::invalid_argument("Rivet async completion handler is empty"); return backend_.set_state_async("counter", detail::encode_Int64(value), [completion = std::move(completion)](rivet::linux_runtime::CallResult raw) mutable { Result<std::int64_t> result; if (raw.error) { result.error = raw.error; } else { try { if (!raw.value) throw std::runtime_error("Rivet async call completed without a value"); result.value = detail::decode_Int64(*raw.value); } catch (...) { result.error = std::current_exception(); } } completion(std::move(result)); }); }

 private:
  rivet::linux_runtime::Backend& backend_;
};

}  // namespace rivet_app
